/// @file
/// @brief Tables of English names popular in 1880 ( "uEngNames.pde" )
/// @details "https://www.ssa.gov/oact/babynames/decades/names1880s.html"
/// @date 2024-09-26 (Last modification)
//*//////////////////////////////////////////////////////////////////////

/// @defgroup More simulation resources
/// @{
//*////////////////////////////////////

/// @brief Few popular, Male & Female fifty-fifty, alphabetic names.
final String[] EnglishNamesShort =   ///< @note Global namespace!
{
  "Arthur", "Blanche","Charles","Diana" , "Elmer",
  "Fannie", "George", "Helen",  "Irene" , "John",
  "Kathie", "Louis",  "Mary",   "Norman", "Olive"
};

/// @brief Male & Female english names from USA Census 1880.
final String[] EnglishNames1880 =    ///< @note Global namespace!
{
"John","Mary",
"William","Anna",
"James","Emma",
"George","Elizabeth",
"Charles","Margaret",
"Frank","Minnie",
"Joseph","Ida",
"Henry","Bertha",
"Robert","Clara",
"Thomas","Alice",
"Edward","Annie",
"Harry","Florence",
"Walter","Bessie",
"Arthur","Grace",
"Fred","Ethel",
"Albert","Sarah",
"Samuel","Ella",
"Clarence","Martha",
"Louis","Nellie",
"David","Mabel",
"Joe","Laura",
"Charlie","Carrie",
"Richard","Cora",
"Ernest","Helen",
"Roy","Maude",
"Will","Lillian",
"Andrew","Gertrude",
"Jesse","Rose",
"Oscar","Edna",
"Willie","Pearl",
"Daniel","Edith",
"Benjamin","Jennie",
"Carl","Hattie",
"Sam","Mattie",
"Alfred","Eva",
"Earl","Julia",
"Peter","Myrtle",
"Elmer","Louise",
"Frederick","Lillie",
"Howard","Jessie",
"Lewis","Frances",
"Ralph","Catherine",
"Herbert","Lula",
"Paul","Lena",
"Lee","Marie",
"Tom","Ada",
"Herman","Josephine",
"Martin","Fannie",
"Jacob","Lucy",
"Michael","Dora",
"Jim","Agnes",
"Claude","Maggie",
"Ben","Blanche",
"Eugene","Katherine",
"Francis","Elsie",
"Grover","Nora",
"Raymond","Mamie",
"Harvey","Rosa",
"Clyde","Stella",
"Edwin","Daisy",
"Edgar","May",
"Ed","Effie",
"Lawrence","Mae",
"Bert","Ellen",
"Chester","Nettie",
"Jack","Ruth",
"Otto","Alma",
"Luther","Della",
"Charley","Lizzie",
"Guy","Sadie",
"Floyd","Sallie",
"Ira","Nancy",
"Ray","Susie",
"Hugh","Maud",
"Isaac","Flora",
"Oliver","Irene",
"Patrick","Etta",
"Homer","Katie",
"Theodore","Lydia",
"Leonard","Lottie",
"Leo","Viola",
"Alexander","Caroline",
"August","Addie",
"Harold","Hazel",
"Allen","Georgia",
"Jessie","Esther",
"Archie","Mollie",
"Philip","Olive",
"Stephen","Willie",
"Horace","Harriet",
"Marion","Emily",
"Bernard","Charlotte",
"Anthony","Amanda",
"Julius","Kathryn",
"Warren","Lulu",
"Leroy","Susan",
"Clifford","Kate",
"Eddie","Nannie",
"Sidney","Jane",
"Milton","Amelia",
"Leon","Virginia",
"Alex","Mildred",
"Lester","Beulah",
"Emil","Eliza",
"Dan","Rebecca",
"Willis","Ollie",
"Everett","Belle",
"Dave","Ruby",
"Leslie","Pauline",
"Rufus","Matilda",
"Alvin","Theresa",
"Perry","Hannah",
"Lloyd","Henrietta",
"Victor","Ora",
"Calvin","Estella",
"Harrison","Leona",
"Norman","Augusta",
"Wesley","Eleanor",
"Jess","Rachel",
"Percy","Amy",
"Amos","Sara",
"Dennis","Anne",
"Jerry","Marion",
"Nathan","Iva",
"Franklin","Ann",
"Alonzo","Nina",
"Matthew","Dorothy",
"Mack","Lola",
"Earnest","Lela",
"Gus","Beatrice",
"Russell","Josie",
"Adam","Sophia",
"Jay","Estelle",
"Wallace","Mayme",
"Otis","Barbara",
"Stanley","Evelyn",
"Adolph","Maria",
"Jake","Inez",
"Roscoe","Allie",
"Maurice","Essie",
"Melvin","Delia",
"Gilbert","Mable",
"Ross","Millie",
"Willard","Alta",
"Mark","Betty",
"Levi","Callie",
"Wilbur","Janie",
"Cornelius","Rosie",
"Aaron","Victoria",
"Jose","Ola",
"Elbert","Gladys",
"Emmett","Louisa",
"Phillip","Ina",
"Morris","Eula",
"Noah","Luella",
"Claud","Vera",
"Clinton","Lou",
"Felix","Celia",
"Moses","Nell",
"Elijah","Goldie",
"Nelson","Winifred",
"Simon","Bettie",
"Lonnie","Hilda",
"Virgil","Sophie",
"Hiram","Christine",
"Jasper","Marguerite",
"Marshall","Tillie",
"Manuel","Birdie",
"Sylvester","Rena",
"Fredrick","Eunice",
"Mike","Bertie",
"Abraham","Olga",
"Silas","Sylvia",
"Irvin","Lucille",
"Max","Bess",
"Owen","Isabelle",
"Christopher","Genevieve",
"Reuben","Leila",
"Glenn","Mathilda",
"Nicholas","Dollie",
"Ellis","Isabel",
"Marvin","Verna",
"Wiley","Bernice",
"Eli","Loretta",
"Edmund","Rhoda",
"Ollie","Cornelia",
"Cecil","Sally",
"Cleveland","Jean",
"Curtis","Alberta",
"Timothy","Winnie",
"Harley","Lelia",
"Jeff","Lois",
"Anton","Myra",
"Alva","Harriett",
"Wilson","Roxie",
"Irving","Adeline",
"Clayton","Abbie",
"Rudolph","Flossie",
"Vernon","Sue",
"Hubert","Christina"
};

/// @brief Female english names from USA Census 1880.
final String[] FemaleEnglishNames1880={    ///< @note Global namespace!
"Mary",
"Anna",
"Emma",
"Elizabeth",
"Margaret",
"Minnie",
"Ida",
"Bertha",
"Clara",
"Alice",
"Annie",
"Florence",
"Bessie",
"Grace",
"Ethel",
"Sarah",
"Ella",
"Martha",
"Nellie",
"Mabel",
"Laura",
"Carrie",
"Cora",
"Helen",
"Maude",
"Lillian",
"Gertrude",
"Rose",
"Edna",
"Pearl",
"Edith",
"Jennie",
"Hattie",
"Mattie",
"Eva",
"Julia",
"Myrtle",
"Louise",
"Lillie",
"Jessie",
"Frances",
"Catherine",
"Lula",
"Lena",
"Marie",
"Ada",
"Josephine",
"Fannie",
"Lucy",
"Dora",
"Agnes",
"Maggie",
"Blanche",
"Katherine",
"Elsie",
"Nora",
"Mamie",
"Rosa",
"Stella",
"Daisy",
"May",
"Effie",
"Mae",
"Ellen",
"Nettie",
"Ruth",
"Alma",
"Della",
"Lizzie",
"Sadie",
"Sallie",
"Nancy",
"Susie",
"Maud",
"Flora",
"Irene",
"Etta",
"Katie",
"Lydia",
"Lottie",
"Viola",
"Caroline",
"Addie",
"Hazel",
"Georgia",
"Esther",
"Mollie",
"Olive",
"Willie",
"Harriet",
"Emily",
"Charlotte",
"Amanda",
"Kathryn",
"Lulu",
"Susan",
"Kate",
"Nannie",
"Jane",
"Amelia",
"Virginia",
"Mildred",
"Beulah",
"Eliza",
"Rebecca",
"Ollie",
"Belle",
"Ruby",
"Pauline",
"Matilda",
"Theresa",
"Hannah",
"Henrietta",
"Ora",
"Estella",
"Leona",
"Augusta",
"Eleanor",
"Rachel",
"Amy",
"Sara",
"Anne",
"Marion",
"Iva",
"Ann",
"Nina",
"Dorothy",
"Lola",
"Lela",
"Beatrice",
"Josie",
"Sophia",
"Estelle",
"Mayme",
"Barbara",
"Evelyn",
"Maria",
"Inez",
"Allie",
"Essie",
"Delia",
"Mable",
"Millie",
"Alta",
"Betty",
"Callie",
"Janie",
"Rosie",
"Victoria",
"Ola",
"Gladys",
"Louisa",
"Ina",
"Eula",
"Luella",
"Vera",
"Lou",
"Celia",
"Nell",
"Goldie",
"Winifred",
"Bettie",
"Hilda",
"Sophie",
"Christine",
"Marguerite",
"Tillie",
"Birdie",
"Rena",
"Eunice",
"Bertie",
"Olga",
"Sylvia",
"Lucille",
"Bess",
"Isabelle",
"Genevieve",
"Leila",
"Mathilda",
"Dollie",
"Isabel",
"Verna",
"Bernice",
"Loretta",
"Rhoda",
"Cornelia",
"Sally",
"Jean",
"Alberta",
"Winnie",
"Lelia",
"Lois",
"Myra",
"Harriett",
"Roxie",
"Adeline",
"Abbie",
"Flossie",
"Sue",
"Christina"
};

/// @brief Male english names from USA Census 1880.
final String[] MaleEnglishNames1880 = {    ///< @note Global namespace!
"John",
"William",
"James",
"George",
"Charles",
"Frank",
"Joseph",
"Henry",
"Robert",
"Thomas",
"Edward",
"Harry",
"Walter",
"Arthur",
"Fred",
"Albert",
"Samuel",
"Clarence",
"Louis",
"David",
"Joe",
"Charlie",
"Richard",
"Ernest",
"Roy",
"Will",
"Andrew",
"Jesse",
"Oscar",
"Willie",
"Daniel",
"Benjamin",
"Carl",
"Sam",
"Alfred",
"Earl",
"Peter",
"Elmer",
"Frederick",
"Howard",
"Lewis",
"Ralph",
"Herbert",
"Paul",
"Lee",
"Tom",
"Herman",
"Martin",
"Jacob",
"Michael",
"Jim",
"Claude",
"Ben",
"Eugene",
"Francis",
"Grover",
"Raymond",
"Harvey",
"Clyde",
"Edwin",
"Edgar",
"Ed",
"Lawrence",
"Bert",
"Chester",
"Jack",
"Otto",
"Luther",
"Charley",
"Guy",
"Floyd",
"Ira",
"Ray",
"Hugh",
"Isaac",
"Oliver",
"Patrick",
"Homer",
"Theodore",
"Leonard",
"Leo",
"Alexander",
"August",
"Harold",
"Allen",
"Jessie",
"Archie",
"Philip",
"Stephen",
"Horace",
"Marion",
"Bernard",
"Anthony",
"Julius",
"Warren",
"Leroy",
"Clifford",
"Eddie",
"Sidney",
"Milton",
"Leon",
"Alex",
"Lester",
"Emil",
"Dan",
"Willis",
"Everett",
"Dave",
"Leslie",
"Rufus",
"Alvin",
"Perry",
"Lloyd",
"Victor",
"Calvin",
"Harrison",
"Norman",
"Wesley",
"Jess",
"Percy",
"Amos",
"Dennis",
"Jerry",
"Nathan",
"Franklin",
"Alonzo",
"Matthew",
"Mack",
"Earnest",
"Gus",
"Russell",
"Adam",
"Jay",
"Wallace",
"Otis",
"Stanley",
"Adolph",
"Jake",
"Roscoe",
"Maurice",
"Melvin",
"Gilbert",
"Ross",
"Willard",
"Mark",
"Levi",
"Wilbur",
"Cornelius",
"Aaron",
"Jose",
"Elbert",
"Emmett",
"Phillip",
"Morris",
"Noah",
"Claud",
"Clinton",
"Felix",
"Moses",
"Elijah",
"Nelson",
"Simon",
"Lonnie",
"Virgil",
"Hiram",
"Jasper",
"Marshall",
"Manuel",
"Sylvester",
"Fredrick",
"Mike",
"Abraham",
"Silas",
"Irvin",
"Max",
"Owen",
"Christopher",
"Reuben",
"Glenn",
"Nicholas",
"Ellis",
"Marvin",
"Wiley",
"Eli",
"Edmund",
"Ollie",
"Cecil",
"Cleveland",
"Curtis",
"Timothy",
"Harley",
"Jeff",
"Anton",
"Alva",
"Wilson",
"Irving",
"Clayton",
"Rudolph",
"Vernon",
"Hubert"
};

//🇺🇲🇬🇧🇦🇺😡🤬👺👹🎃🚺🚹

final String[] EnglishInsults = ///< @note Global namespace! 
{
"airhead","1",    // American English offensive! a silly, stupid person
"arsehole","3",   //vvv
"asshole","3",    // taboo!!! a selfish, unpleasant, obnoxious person
"ass-kisser","3", // American English taboo!!! someone who says nice things to someone in order to get something from them
"bastard","1",    // offensive! an unpleasant, despicable person
"bimbo","0",      // a pretty, but empty-headed, young lady
"bugger","2",     // British and Australian English vulgar!! a disliked or pitiful person, usually a man
"chicken","0",    // a coward (n.) | cowardly (adj.)
"dag","1",        // Australian English offensive! an unfashionable or socially awkward person
"dago","3",       // taboo!!! a derogatory word for a person from Italy, Spain, Portugal or South America
"deadbeat","0",   // a dull, lazy, unreliable person
"dickhead","1",   // offensive! an unpleasant or annoying person
"donkey","0",     // American and Australian English a stupid or silly person
"dope","0",       // a stupid person, a fool
"dork","1",       // American English offensive! a socially awkward person
"dweeb","1",      // American English offensive! a studious but socially inept person
"flake","0",      // American English, an unreliable person who says they'll do something, but then doesn't do it
"floozy","0",     //vvv
"floozie","0",    //vvv
"floosie","0",    // a girl or woman with a reputation for sleeping with many people
"freak","0",      // a strange person
"fruitcake","1",  // offensive! a crazy or eccentric person
"gasbag","0",     // a person who talks too much
"geek","0",       // a computer and IT expert
"geezer","1",     // offensive! an old person
"git","1",        // British English offensive! a fool, a stupid person
"goose","0",      // a silly or stupid person
"hick","1",       // American English offensive! a rural person regarded as uneducated and mentally slow (n.) | provincial or rural (adj.)
"honky","1",      // American English offensive! a derogatory term in black American slang for a white person
"jerk","1",       // offensive! a stupid person
"kike","3",       // American English taboo!!! a derogatory word meaning a Jewish person
"klutz","1",      // American and Australian English offensive! a clumsy or foolish person
"kook","0",       // American English, a strange or eccentric person
"lardass","1",    // American English offensive! an overweight person, esp. one with large buttocks
"limey","1",      // offensive! a derogatory word meaning a British person (n.) | British (adj.)
"loudmouth","0",  // an obnoxious person who talks too much and too loudly
"louse","1",      // American English offensive! an unpleasant or nasty person
"meathead","1",   // offensive! a stupid person
"nerd","1",       // offensive! a studious person with few social skills
"nut","1",        //vvv
"nutter","1",     // British English offensive! a crazy or strange person
"old bat","0",    // an unpleasant old woman
"pig","1",        // offensive! an unattractive and unpleasant person
"poof","1",       //vvv
"poofter","1",    // offensive! an offensive, derogatory word meaning a gay man
"prat","1",       // British English offensive! a fool
"psycho","0",     // "crazy", insane
"rat","0",        // a horrible, nasty person
"redneck","1",    // American English offensive! a lower-class white person from a rural background
"scum","0",       //vvv
"scumbag","0",    // a worthless or very disliked person
"sicko","0",      // a deranged or perverted person
"smart-arse","1", // British English offensive! a person who's annoying because they try to show how clever and knowledgeable they are (n.) | having an annoying way of trying to seem clever (adj.)
"smart-ass","1",  // American English offensive!a person who's annoying because they try to show how clever and knowledgeable they are (n.) | having an annoying way of trying to seem clever (adj.)
"tight-arse","1", // Australian English offensive! a person who doesn't like spending money, especially on other people
"tight-ass","1",  // American English offensive! sby who spends as little money as possible, a miser 2) sby who's repressed and very strict about following society's rules
"toff","0",       // British English, a wealthy, upper-class person
"tool","1",       // offensive! a stupid person
"twerp","1",      //vvv
"twirp","1",      // offensive! a silly, immature person
"twit","1",       // offensive! a silly, stupid person
"wanker","1",     // offensive! an arrogant or pretentious person
"weirdo","0",     // a strange, eccentric or weird person
"wimp","0",       // a weak, unassertive person
"wog","3",        // British English taboo!!! an offensive, derogatory term for a person whose skin colour is not white
"wop","3",        // taboo!!! a derogatory term for a person from southern Europe, especially an Italian
"yahoo","0",      // a rude, loud, aggressive person
"yid","3",        //vvv
"Yid","3",        // taboo!!! an offensive, derogatory word meaning a Jewish person
"yob","1",        //vvv
"yobbo","1",      // British English offensive! an aggressive, impolite, crude person
"yokel","1",      // offensive! a simple, poorly-educated person from the countryside
"zero","0",       // a worthless person, someone who's done nothing worthwhile in life
};

//*/////////////////////////////////////////////////////////////////////
//*  ->"https://www.researchgate.net/profile/WOJCIECH_BORKOWSKI" 
//*   - OPTIONAL TOOLS: DATA
//*  ->"https://github.com/borkowsk/sym4processing"
/// @}
//*/////////////////////////////////////////////////////////////////////
