/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_AbsHighPassFilter_INCLUDED
#define HEADER_AbsHighPassFilter_INCLUDED

/**
* @brief Absolute High Pass Filter.
*        highPassFilter filtering links with higher absolute value of weight.
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: AbsHighPassFilter

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:AbsHighPassFilter

class AbsHighPassFilter : public  LinkFilter , public virtual Object{
  public:

  float treshold;
  AbsHighPassFilter(float tres) {
	 treshold=std::abs(tres);
	}
  bool    meetsTheAssumptions(piLink l) {
	 return std::abs(l->getWeight())>treshold;
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_AbsHighPassFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

