/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_AllLinks_INCLUDED
#define HEADER_AllLinks_INCLUDED

/**
* @brief Simplest link filtering class which accepts all links.
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: AllLinks

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:AllLinks

class AllLinks : public  LinkFilter , public virtual Object{
  public:

  bool    meetsTheAssumptions(piLink l) {
	 return true;
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_AllLinks_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

