/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_Colorable_INCLUDED
#define HEADER_Colorable_INCLUDED

/**
* @brief Abstraction for any colorable object->Only for visualisation.
*/

#include "iColorable_class.pde.hpp"

#include "Named_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: Colorable

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:Colorable

//abstract
class Colorable : public  Named, public virtual iColorable , public virtual Object{
  public:

  virtual  void   applyFill(float modifier) {
	assert(false );	//  "Pure virtual    `applyFill()` called";
	}
  virtual  void applyStroke(float modifier) {
	assert(false );	//  "Pure virtual  `applyStroke()` called";
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Colorable_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

