/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_HighPassFilter_INCLUDED
#define HEADER_HighPassFilter_INCLUDED

/**
* @brief High Pass Filter.
*        Class which filters links with higher weights.
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: HighPassFilter

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:HighPassFilter

class HighPassFilter : public  LinkFilter , public virtual Object{
  public:

  float treshold;
  HighPassFilter(float tres) {
	 treshold=tres;
	}
  bool    meetsTheAssumptions(piLink l) {
	 return l->getWeight()>treshold;
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_HighPassFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

