/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_i2DDataSample_INCLUDED
#define HEADER_i2DDataSample_INCLUDED

/** @brief Interface of 2D sample of data (ex. 2D histogram data, map of simulation cells etc... ). */

#include "iFloatValues2IndexedContainer_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: i2DDataSample

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:i2DDataSample

//interface
class i2DDataSample  : public virtual  iFloatValues2IndexedContainer, public virtual  i2IndexedFloatConsiderer, public virtual  iFloatRange, public virtual  iOptionsSet , public virtual Object{
  public:

  virtual  piIntPair   whereMin() =0; //!< ADDED
  virtual  piIntPair   whereMax() =0; //!< ADDED
  virtual  void       consider(int indexR,int indexC,float value) =0; //!< It takes another triplet and updates results.
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_i2DDataSample_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

