/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_i2IndexedFloatConsiderer_INCLUDED
#define HEADER_i2IndexedFloatConsiderer_INCLUDED

/** @brief Interface of any class witch can take a float value connected with int label for any processing. */

/// @note Automatically extracted definition of `class`: i2IndexedFloatConsiderer
//interface
class i2IndexedFloatConsiderer: public virtual Object{
  public:

   virtual  void      consider(int label1,int label2,float value) =0; //!< It takes another triplet and updates results.
}  ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_i2IndexedFloatConsiderer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

