/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iBasicStatistics_INCLUDED
#define HEADER_iBasicStatistics_INCLUDED

/** Statistics of raw data samples. */

/// @note Automatically extracted definition of `class`: iBasicStatistics
//interface
class iBasicStatistics: public virtual Object{
  public:

  virtual  float       getMean() =0; //!< Access to the current average.
  virtual  float   getHarmMean() =0; //!< Calculation of current harmonic mean.
  virtual  float   getQuadMean() =0; //!< Calculation of current mean square.
 
  /// @brief Calculation of current average with arbitrary powers.
  /// @note  It can be both a fraction and a number greater than 2, e->g. 1/3 or 3.
  virtual  float    getPowMean(float power) =0; //!< @param 'power' is the given averaging power.
  
  /// @brief Calculation of standard deviation.
  virtual  float     getStdDev() =0;
   
  /// @brief Calculates the median of the entire data series.
  /// @note  Requires copying and sorting,
  ///        so it can be very computationally expensive.
  virtual  float     getMedian() =0;  
    
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iBasicStatistics_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

