/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iColor_INCLUDED
#define HEADER_iColor_INCLUDED

/** @brief Forcing remembering full color inside object. */

/// @note Automatically extracted definition of `class`: iColor
//interface
class iColor: public virtual Object{
  public:

  virtual  void   setColor(color fullColor) =0;
  virtual  color  getColor() =0;
} ;//_EofCl iColor

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iColor_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

