/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iColorable_INCLUDED
#define HEADER_iColorable_INCLUDED

/** @brief Forcing `applyFill` & `applyStroke` methods for visualisation. */

/// @note Automatically extracted definition of `class`: iColorable
//interface
class iColorable: public virtual Object{
  public:
 //TODO iColoriser
  virtual  void   applyFill(float intensity) =0;
  virtual  void applyStroke(float intensity) =0;
} ;//_EofCl iColorable

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iColorable_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

