/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iDescribable_INCLUDED
#define HEADER_iDescribable_INCLUDED

/** @brief Any object which have description as (maybe) long, multi line string. */

/// @note Automatically extracted definition of `class`: iDescribable
//interface
class iDescribable: public virtual Object{
  public:
 
  virtual  String    getDescription() =0;
  virtual  String       description() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iDescribable_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

