/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatValues2IndexedContainer_INCLUDED
#define HEADER_iFloatValues2IndexedContainer_INCLUDED

/** @brief Any recangular (2*int indexed) container of floats. */

#include "iResetable_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatValues2IndexedContainer

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatValues2IndexedContainer

//interface
class iFloatValues2IndexedContainer : public virtual  iResetable , public virtual Object{
  public:

  ///  *  `_interfunc int   numOfElements() =0;` -- Series length=whole size->Together with empty cells, i->e. == INVALID_INDEX.
  ///  *  `_interfunc int            size() =0;` -- Series length=whole size->Together with empty cells, i->e. == INVALID_INDEX.
  ///  *  `_interfunc float  getElementAt(int index) =0;` -- Value at particular index->May return INF_NOT_EXIST.
  ///  *  `_interfunc float           get(int index) =0;` -- Value at particular index->May return INF_NOT_EXIST.
  virtual  int       numOfRows() =0; //!< Number of rows in such a virtual matrix
  virtual  int            rows() =0; //!< Number of rows in such a virtual matrix
  virtual  int    numOfColumns() =0; //!< Number of columns in such a virtual matrix
  virtual  int         columns() =0; //!< Number of columns in such a virtual matrix
  virtual  float  getElementAt(int indexR,int indexC) =0; //!< Value at particular index->May return INF_NOT_EXIST.
  virtual  float           get(int indexR,int indexC) =0; //!< Value at particular index->May return INF_NOT_EXIST.
  virtual  void      replaceAt(int indexR,int indexC,float value) =0;
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatValues2IndexedContainer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

