/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatPair_INCLUDED
#define HEADER_iFloatPair_INCLUDED

/// @note Automatically extracted definition of `class`: iFloatPair
//interface
class iFloatPair: public virtual Object{
  public:

  virtual  float               get1() =0;
  virtual  float               get2() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatPair_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

