/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatPoint2D_INCLUDED
#define HEADER_iFloatPoint2D_INCLUDED

/** @brief Interface forces getters for X & Y ... */

/// @note Automatically extracted definition of `class`: iFloatPoint2D
//interface
class iFloatPoint2D: public virtual Object{
  public:

  virtual  float               getX() =0;
  virtual  float               getY() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatPoint2D_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

