/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatPoint3D_INCLUDED
#define HEADER_iFloatPoint3D_INCLUDED

/** @brief Interface forces getter for Z and also what is derived from base class. */

#include "iFloatPoint2D_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatPoint3D

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatPoint3D

//interface
class iFloatPoint3D : public virtual  iFloatPoint2D , public virtual Object{
  public:

 virtual  float                getZ() =0;
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatPoint3D_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

