/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatPoint4D_INCLUDED
#define HEADER_iFloatPoint4D_INCLUDED

/** @brief Interface forces getters for T ("time") and also what is derived from base class. */

#include "iFloatPoint3D_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatPoint4D

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatPoint4D

//interface
class iFloatPoint4D : public virtual  iFloatPoint3D , public virtual Object{
  public:

 virtual  float                getT() =0;
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatPoint4D_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

