/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatRange_INCLUDED
#define HEADER_iFloatRange_INCLUDED

/** @brief Any range spanned from `Min` to `Max`. */

#include "iFloatConsiderer_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatRange

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatRange

//interface
class iFloatRange : public virtual  iFloatConsiderer , public virtual Object{
  public:

///  *  `_interfunc void      consider(float value) =0;` -- Derived: It takes another value and updates range if needed.
  virtual  float       getMin() =0; //MIN_RANGE_VALUE?
  virtual  float       getMax() =0; //MAX_RANGE_VALUE?
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatRange_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

