/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatValuesIndexedContainer_INCLUDED
#define HEADER_iFloatValuesIndexedContainer_INCLUDED

/** @brief Any linear (indexed) container of floats. */

#include "iResetable_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatValuesIndexedContainer

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatValuesIndexedContainer

//interface
class iFloatValuesIndexedContainer : public virtual  iResetable , public virtual Object{
  public:

  virtual  int   numOfElements() =0; //!< Series length->Together with empty cells, i->e. == INVALID_INDEX.
  virtual  int            size() =0; //!< Series length->Together with empty cells, i->e. == INVALID_INDEX.
  virtual  float  getElementAt(int index) =0; //!< Value at particular index->May return INF_NOT_EXIST.
  virtual  float           get(int index) =0; //!< Value at particular index->May return INF_NOT_EXIST.
  virtual  void      replaceAt(int index,float value) =0;
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatValuesIndexedContainer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

