/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatFunction1D_INCLUDED
#define HEADER_iFloatFunction1D_INCLUDED

/** @brief A function of one value in the form of a class - a functor. */

/// @note Automatically extracted definition of `class`: iFloatFunction1D
//interface
class iFloatFunction1D: public virtual Object{
  public:

  virtual  float     calculate(float X) =0;
  virtual  float        getMin() =0; //!< MIN_RANGE_VALUE?
  virtual  float        getMax() =0; //!< Always must be different!
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatFunction1D_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

