/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatConsiderer_INCLUDED
#define HEADER_iFloatConsiderer_INCLUDED

/** @brief Interface of any class witch can take a float value for any processing. */

/// @note Automatically extracted definition of `class`: iFloatConsiderer
//interface
class iFloatConsiderer: public virtual Object{
  public:

    virtual  void     consider(float value) =0; //!< It takes another value and updates results.
}  ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatConsiderer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

