/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFloatRangeWithValue_INCLUDED
#define HEADER_iFloatRangeWithValue_INCLUDED

/** @brief Ane range with associated value, e->g->MARKED RANGE. */

#include "iFloatRange_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iFloatRangeWithValue

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iFloatRangeWithValue

//interface
class iFloatRangeWithValue : public virtual  iFloatRange, public virtual  iFloatValue , public virtual Object{
  public:

  /// Derived methods:
  ///  *  `_interfunc void      consider(float value) =0;` //!< It takes another value and updates range if needed.
  ///  *  `_interfunc float       getMin() =0; -- MIN_RANGE_VALUE?`
  ///  *  `_interfunc float       getMax() =0; -- MAX_RANGE_VALUE?`
  virtual  float          get() =0; //!< value releated to the range
} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFloatRangeWithValue_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

