/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iFreqStatistics_INCLUDED
#define HEADER_iFreqStatistics_INCLUDED

/** Statistics for counters data sets. */

/// @note Automatically extracted definition of `class`: iFreqStatistics
//interface
class iFreqStatistics: public virtual Object{
  public:

  /// @brief It calculates "Gini coefficient".
  /// @details Difference algorithm from "https://en->wikipedia.org/wiki/Gini_coefficient"
  /// @note It requires copying to the table because there may be missing values in the list.
  virtual  float getGiniCoefficient() =0;
  
    
  /// @details In information theory, the entropy of a random variable is the average level of 
  ///         "information", "surprise", or "uncertainty" inherent to the variable's possible outcomes.
  ///         See: https://en->wikipedia->org/wiki/Entropy_(information_theory)
  virtual  float getShannonEntropy() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iFreqStatistics_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

