/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iIndexedFloatConsiderer_INCLUDED
#define HEADER_iIndexedFloatConsiderer_INCLUDED

/** @brief Interface of any class witch can take a float value connected with int label for any processing. */

/// @note Automatically extracted definition of `class`: iIndexedFloatConsiderer
//interface
class iIndexedFloatConsiderer: public virtual Object{
  public:

   virtual  void      consider(int label,float value) =0; //!< It takes another pair and updates results.
}  ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iIndexedFloatConsiderer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

