/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iIntValue_INCLUDED
#define HEADER_iIntValue_INCLUDED

/** @brief Interface forces getter for single int. */

/// @note Automatically extracted definition of `class`: iIntValue
//interface
class iIntValue: public virtual Object{
  public:

  virtual  int                  get() =0;
} ;//_EofCl  

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iIntValue_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

