/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iLinkFactory_INCLUDED
#define HEADER_iLinkFactory_INCLUDED

/**
* @brief Any factory producing links.
*/

/// @note Automatically extracted definition of `class`: iLinkFactory
//interface
class iLinkFactory: public virtual Object{
  public:

  virtual  piLink  makeLink(piNode Source,piNode Target) =0;
  virtual  piLink  makeSelfLink(piNode Self) =0;     
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iLinkFactory_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

