/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iLink_INCLUDED
#define HEADER_iLink_INCLUDED

/**
* @brief Network connection/link interface.
*/

/// @note Automatically extracted definition of `class`: iLink
//interface
class iLink: public virtual Object{
  public:
 
  virtual  float     getWeight() /*_forcbody*/;
  virtual  int   getTypeMarker() /*_forcbody*/;
  virtual  piNode     getTarget() /*_forcbody*/;
  virtual  void      setTarget(piNode tar) /*_forcbody*/;
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iLink_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

