/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iLinkFilter_INCLUDED
#define HEADER_iLinkFilter_INCLUDED

/**
* @brief Interface for any filter for links.
*/

/// @note Automatically extracted definition of `class`: iLinkFilter
//interface
class iLinkFilter: public virtual Object{
  public:

  virtual  bool    meetsTheAssumptions(piLink l)/*_forcbody*/;
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iLinkFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

