/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iModelTimer_INCLUDED
#define HEADER_iModelTimer_INCLUDED

/** @brief Model time measuring interface */

/// @note Automatically extracted definition of `class`: iModelTimer
//interface
class iModelTimer: public virtual Object{
  public:

  virtual  float                getCurrentStep() =0; //!< On some models the step number may sometimes increase by fractions!
  virtual  float                getCurrentTime() =0; //!< Step count and simulated time may not be in a straight relationship.
  virtual  float                getLastStepTime() =0;
  virtual  float                getMeanStepTime() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iModelTimer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

