/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iNamed_INCLUDED
#define HEADER_iNamed_INCLUDED

/** @brief It forces name of an object available as `String` (planty of usage). */

/// @note Automatically extracted definition of `class`: iNamed
//interface
class iNamed: public virtual Object{
  public:

  virtual  String           getName() =0;
  virtual  String              name() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iNamed_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

