/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iNode_INCLUDED
#define HEADER_iNode_INCLUDED

/**
* @brief Network node interface.
*        "Conn" below is a shortage from Connection.
* @note Somewhere may uses class Link not interface iLink because of efficiency!
*/

#include "iNamed_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iNode

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iNode

//interface
class iNode : public virtual  iNamed , public virtual Object{
  public:

  virtual  int      numOfConn()         /*_forcbody*/;
  virtual  int        addConn(piLink  l) /*_forcbody*/;
  virtual  int        delConn(piLink  l) /*_forcbody*/;

  virtual  piLink      getConn(int    i) /*_forcbody*/;
  virtual  piLink      getConn(piNode  n) /*_forcbody*/;
  virtual  piLink      getConn(String k) /*_forcbody*/;
  virtual  sarray<piLink>    getConns(piLinkFilter f) /*_forcbody*/;
} ; //_EndOfClass_


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iNode_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

