/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iOptionsSet_INCLUDED
#define HEADER_iOptionsSet_INCLUDED

/** @brief interface to set of flag identified by binary masks */

/// @note Automatically extracted definition of `class`: iOptionsSet
//interface
class iOptionsSet: public virtual Object{
  public:

  virtual  bool      isOption(int mask) =0; //!< It checks the options according to masks.
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iOptionsSet_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

