/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iRangeWithValueConsiderer_INCLUDED
#define HEADER_iRangeWithValueConsiderer_INCLUDED

/** @brief Interface of any class witch can take a `rangeWithValue` for any processing */

/// @note Automatically extracted definition of `class`: iRangeWithValueConsiderer
//interface
class iRangeWithValueConsiderer: public virtual Object{
  public:

virtual  void         consider(piFloatRangeWithValue range) =0; //!< It takes and use another range.
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iRangeWithValueConsiderer_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

