/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iRangesDataSample_INCLUDED
#define HEADER_iRangesDataSample_INCLUDED

/** @brief Interface for sample of ranges data. */

#include "iFloatRangesWithValueContainer_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iRangesDataSample

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iRangesDataSample

//interface
class iRangesDataSample : public virtual  iFloatRangesWithValueContainer, public virtual  iRangeWithValueConsiderer , public virtual Object{
  public:

  ///*  `_interfunc void                 consider(piFloatRangeWithValue range) =0;` -- Derived: It takes and use another range.
  virtual  int       whereMin() =0; //!< ADDED
  virtual  int       whereMax() =0; //!< ADDED

} ;//_EofCl

//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iRangesDataSample_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

