/// @file
#pragma once
/// @date 2024-10-21 (last modification)                       @author borkowsk
#ifndef HEADER_iResetable_INCLUDED
#define HEADER_iResetable_INCLUDED

/** @brief Any object which can go back to initial state without additional parameters */

/// @note Automatically extracted definition of `class`: iResetable
//interface
class iResetable: public virtual Object{
  public:

  virtual  void               reset() =0;
} ;//_EofCl

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iResetable_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

