/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iVisLink_INCLUDED
#define HEADER_iVisLink_INCLUDED

/**
* @brief Visualisable network connection.
*/

#include "iLink_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iVisLink

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iVisLink

//interface
class  iVisLink : public virtual  iLink,iNamed,iColorable , public virtual Object{
  public:

  virtual  color     defColor() =0;
  virtual  piVisNode  getVisTarget() /*_forcbody*/;
} ; //_EndOfClass_


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iVisLink_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

