/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_iVisNode_INCLUDED
#define HEADER_iVisNode_INCLUDED

/**
* @brief Visualisable network node.
*/

#include "iNode_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: iVisNode

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:iVisNode

//interface
class iVisNode : public virtual  iNode,iNamed,iColorable,iPositioned , public virtual Object{
  public:

  /// @brief It provides default color.
  virtual  color     defColor() =0;
} ; //_EndOfClass_


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_iVisNode_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

