/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_LinkFilter_INCLUDED
#define HEADER_LinkFilter_INCLUDED

/**
* @brief Abstraction of link filtering class.
*/

#include "iLinkFilter_class.pde.hpp"

/// @note Automatically extracted definition of `class`: LinkFilter
//abstract
class LinkFilter : public virtual iLinkFilter , public virtual Object{
  public:

  virtual  bool    meetsTheAssumptions(piLink l)
                  {
	assert(false );	//  "Pure virtual  meetsTheAssumptions(Link) called";
 	return  false;
	}
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_LinkFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

