/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_LinkFactory_INCLUDED
#define HEADER_LinkFactory_INCLUDED

/**
* @brief Abstraction of link factory class->Forcing `makeLink()` and `makeSalfLink()` methods.
*/

#include "iLinkFactory_class.pde.hpp"

/// @note Automatically extracted definition of `class`: LinkFactory
//abstract
class LinkFactory : public virtual iLinkFactory , public virtual Object{
  public:

  virtual  piLink  makeLink(piNode Source,piNode Target)
                  {
	assert(false );	//  "Pure virtual  make(Node,Node) called";
 	return  nullptr;
	}
                 piLink  makeSelfLink(piNode Self)
                  {
	assert(false );	//  "Pure virtual  make(Node) called";
 	return  nullptr;
	} //<>//
} ; //_EndOfClass


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_LinkFactory_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

