/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_Named_INCLUDED
#define HEADER_Named_INCLUDED

/**
* @brief Abstraction of string-named class->Forcing `name()` method for visualisation and mapping.
*/

#include "iNamed_class.pde.hpp"

/// @note Automatically extracted definition of `class`: Named
//abstract
class Named : public virtual iNamed , public virtual Object{
  public:
       
  virtual  String    name(){assert(false );	//  "Pure interface name() called";
 	return  nullptr;}
} ; //_EndOfClass


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Named_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

