/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_OrFilter_INCLUDED
#define HEADER_OrFilter_INCLUDED

/**
* @brief `OR` on two filters assembly class.
*        A class for logically joining two filters with the OR operator.
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: OrFilter

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:OrFilter

class OrFilter : public  LinkFilter , public virtual Object{
  public:

   pLinkFilter a;
   pLinkFilter b;
   OrFilter(pLinkFilter aa,pLinkFilter bb){a=aa;b=bb;}
   bool    meetsTheAssumptions(piLink l) 
   { 
     return a->meetsTheAssumptions(l) || b->meetsTheAssumptions(l);
   }
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_OrFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

