/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_pointxy_INCLUDED
#define HEADER_pointxy_INCLUDED

/// @brief A class to represent two-dimensional points.

/// @note Automatically extracted definition of `class`: pointxy
class pointxy: public virtual Object{
  public:

  float x,y;
  
  pointxy()
  {
    x=y=0;
  }
  
  pointxy(float ix,float iy)
  {
    x=ix;y=iy;
  }
} ; //_EndOfClass


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_pointxy_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

