/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_Positioned_INCLUDED
#define HEADER_Positioned_INCLUDED

/**
* @brief Forcing `posX()` & `posY()` & `posZ()` methods for visualisation and mapping.
*/

#include "iPositioned_class.pde.hpp"

#include "Colorable_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: Positioned

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:Positioned

//abstract
class Positioned : public  Colorable, public virtual iPositioned , public virtual Object{
  public:

  virtual  float    posX(){assert(false );	//  "Pure virtual  posX() called";
 	return  0;}
  virtual  float    posY(){assert(false );	//  "Pure virtual  posY() called";
 	return  0;}
  virtual  float    posZ(){assert(false );	//  "Pure virtual  posZ() called";
 	return  0;}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Positioned_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

