/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_randomWeightLinkFactory_INCLUDED
#define HEADER_randomWeightLinkFactory_INCLUDED

/**
* @brief Random link factory.
*        It creates links with random weights.
*/

#include "iLinkFactory_class.pde.hpp"

/// @note Automatically extracted definition of `class`: randomWeightLinkFactory
class randomWeightLinkFactory : public virtual iLinkFactory , public virtual Object{
  public:

  float min_weight,max_weight;
  int   default_type;
  
  /// @brief Constructor for setting up requirements.
  randomWeightLinkFactory(float min_we,float max_we,int def_type)
  { 
    min_weight=min_we;max_weight=max_we;
    default_type=def_type;
  }
  
  /// @brief Real factory product: "to `Target` link".
  /// @param `Source` is ignored here, but is required by interface for other usage.
  /// @param `Target` - mandatory! 
  pLink  makeLink(piNode Source,piNode Target)
  {
    return new Link((Node)Target,random(min_weight,max_weight),default_type);
  }
  
  /// @brief Special factory product - self link.
  pLink  makeSelfLink(piNode Self)
  {
    return new Link((Node)Self,random(min_weight,max_weight),default_type);
  }
  
} ; //_EndOfClass


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_randomWeightLinkFactory_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

