/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_settings_bar3d_INCLUDED
#define HEADER_settings_bar3d_INCLUDED

/// @brief Configuration set of BAR3D visualisation.

/// @note Automatically extracted definition of `class`: settings_bar3d
class settings_bar3d: public virtual Object{
  public:

int a=10;
int b=6;
int c=6;
color wire=color(255,255,255); //Kolor ramek
color back=color(0,0,0); //Informacja o kolorze tla
} ; //_EndOfClass


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_settings_bar3d_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

