/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_TypeAndAbsHighPassFilter_INCLUDED
#define HEADER_TypeAndAbsHighPassFilter_INCLUDED

/**
* @brief Special type of filter for efficient visualisation.
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: TypeAndAbsHighPassFilter

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:TypeAndAbsHighPassFilter

class TypeAndAbsHighPassFilter  : public  LinkFilter , public virtual Object{
  public:

  int ltype;
  float treshold;
  TypeAndAbsHighPassFilter(){ ltype=-1;treshold=0;}
  TypeAndAbsHighPassFilter(int t,float tres) {
	 ltype=t;treshold=tres;
	}
  pTypeAndAbsHighPassFilter reset(int t,float tres) {
	 ltype=t;treshold=tres;
	return  this;
	}
  bool    meetsTheAssumptions(piLink l) {
	 return l->getTypeMarker()==ltype && std::abs(l->getWeight())>treshold;
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_TypeAndAbsHighPassFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

