/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_TypeFilter_INCLUDED
#define HEADER_TypeFilter_INCLUDED

/**
* @brief Type of link filter.
*        Class which filters links of specific "color"/"type".
*/

#include "LinkFilter_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: TypeFilter

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:TypeFilter

class TypeFilter : public  LinkFilter , public virtual Object{
  public:

  int ltype;
  TypeFilter(int t) {
	 ltype=t;
	}
  bool    meetsTheAssumptions(piLink l) {
	 return l->getTypeMarker()==ltype;
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_TypeFilter_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

