/// @file
#pragma once
/// @date 2024-10-21 (last modification)
#ifndef HEADER_Visual2DNodeAsMap_INCLUDED
#define HEADER_Visual2DNodeAsMap_INCLUDED

/**
* @brief Visualisable node based on `NodeAsMap` core.
*        It : public virtual all things needed for visualisation.
*/

#include "iVisNode_class.pde.hpp"

#include "NodeAsMap_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: Visual2DNodeAsMap

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:Visual2DNodeAsMap

class Visual2DNodeAsMap : public  NodeAsMap, public virtual iVisNode , public virtual Object{
  public:

  float X=0;
  float Y=0;
  color fillc=0x0;
  color strok=0x0;
  
  Visual2DNodeAsMap(float x, float y) { super();
    X=x; Y=y;  
  }
 
  void setFill(float intensity) {
	 fill(fillc,intensity); 
	}
  void setStroke(float intensity) {
	 stroke(strok,intensity); 
	}
  float  posX() {
	 return X;
	}
  float  posY() {
	 return Y;
	}
  String name() {
	 return (String("(")+X+String(",")+Y+String(")")+this);
	}
} ; //_EndOfClass


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Visual2DNodeAsMap_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-21 19:06:46 !

